apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    project: expense
    module: bckend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
  